# coding: utf-8
from model.serializable import SwaggerSerializable


class CustomerUpdatableData(SwaggerSerializable):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'phone': 'str',
        'email': 'str'
    }

    attribute_map = {
        'phone': 'phone',
        'email': 'email'
    }

    def __init__(self, phone=None, email=None):  # noqa: E501
        """CustomerUpdatableData - a model defined in Swagger"""  # noqa: E501
        self._phone = None
        self._email = None
        self.discriminator = None
        if phone is not None:
            self.phone = phone
        if email is not None:
            self.email = email

    @property
    def phone(self):
        """Gets the phone of this CustomerUpdatableData.  # noqa: E501

        The customer's contact phone number.<br />If **SMS Cardholder Receipts** feature is enabled in the terminal, We will use this number to automatically send the receipts of eventual transactions.  # noqa: E501

        :return: The phone of this CustomerUpdatableData.  # noqa: E501
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone):
        """Sets the phone of this CustomerUpdatableData.

        The customer's contact phone number.<br />If **SMS Cardholder Receipts** feature is enabled in the terminal, We will use this number to automatically send the receipts of eventual transactions.  # noqa: E501

        :param phone: The phone of this CustomerUpdatableData.  # noqa: E501
        :type: str
        """

        self._phone = phone

    @property
    def email(self):
        """Gets the email of this CustomerUpdatableData.  # noqa: E501

        The customer's contact email address.<br />If **Email Cardholder Receipt** feature is enabled in the terminal, We will use this address to automatically send the receipts of eventual transactions.  # noqa: E501

        :return: The email of this CustomerUpdatableData.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this CustomerUpdatableData.

        The customer's contact email address.<br />If **Email Cardholder Receipt** feature is enabled in the terminal, We will use this address to automatically send the receipts of eventual transactions.  # noqa: E501

        :param email: The email of this CustomerUpdatableData.  # noqa: E501
        :type: str
        """

        self._email = email
