# coding: utf-8

from model.serializable import SwaggerSerializable


class IpAddress(SwaggerSerializable):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ipv4': 'str',
        'ipv6': 'str'
    }

    attribute_map = {
        'ipv4': 'ipv4',
        'ipv6': 'ipv6'
    }

    def __init__(self, ipv4=None, ipv6=None):  # noqa: E501
        """IpAddress - a model defined in Swagger"""  # noqa: E501
        self._ipv4 = None
        self._ipv6 = None
        self.discriminator = None
        if ipv4 is not None:
            self.ipv4 = ipv4
        if ipv6 is not None:
            self.ipv6 = ipv6

    @property
    def ipv4(self):
        """Gets the ipv4 of this IpAddress.  # noqa: E501

        IP address in the Internet Protocol Version 4 Format.  # noqa: E501

        :return: The ipv4 of this IpAddress.  # noqa: E501
        :rtype: str
        """
        return self._ipv4

    @ipv4.setter
    def ipv4(self, ipv4):
        """Sets the ipv4 of this IpAddress.

        IP address in the Internet Protocol Version 4 Format.  # noqa: E501

        :param ipv4: The ipv4 of this IpAddress.  # noqa: E501
        :type: str
        """

        self._ipv4 = ipv4

    @property
    def ipv6(self):
        """Gets the ipv6 of this IpAddress.  # noqa: E501

        IP address in the Internet Protocol Version 6 Format  # noqa: E501

        :return: The ipv6 of this IpAddress.  # noqa: E501
        :rtype: str
        """
        return self._ipv6

    @ipv6.setter
    def ipv6(self, ipv6):
        """Sets the ipv6 of this IpAddress.

        IP address in the Internet Protocol Version 6 Format  # noqa: E501

        :param ipv6: The ipv6 of this IpAddress.  # noqa: E501
        :type: str
        """

        self._ipv6 = ipv6
