# coding: utf-8

from model.serializable import SwaggerSerializable


class OfflineProcessing(SwaggerSerializable):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'operation': 'str',
        'approval_code': 'str'
    }

    attribute_map = {
        'operation': 'operation',
        'approval_code': 'approvalCode'
    }

    def __init__(self, operation=None, approval_code=None):  # noqa: E501
        """OfflineProcessing - a model defined in Swagger"""  # noqa: E501
        self._operation = None
        self._approval_code = None
        self.discriminator = None
        if operation is not None:
            self.operation = operation
        if approval_code is not None:
            self.approval_code = approval_code

    @property
    def operation(self):
        """Gets the operation of this OfflineProcessing.  # noqa: E501


        :return: The operation of this OfflineProcessing.  # noqa: E501
        :rtype: str
        """
        return self._operation

    @operation.setter
    def operation(self, operation):
        """Sets the operation of this OfflineProcessing.


        :param operation: The operation of this OfflineProcessing.  # noqa: E501
        :type: str
        """
        self._operation = operation

    @property
    def approval_code(self):
        """Gets the approval_code of this OfflineProcessing.  # noqa: E501

        Approval code provided by the payment processor for the specific transaction.<br />Use this field combined with `OFFLINE_APPROVAL` operation.  # noqa: E501

        :return: The approval_code of this OfflineProcessing.  # noqa: E501
        :rtype: str
        """
        return self._approval_code

    @approval_code.setter
    def approval_code(self, approval_code):
        """Sets the approval_code of this OfflineProcessing.

        Approval code provided by the payment processor for the specific transaction.<br />Use this field combined with `OFFLINE_APPROVAL` operation.  # noqa: E501

        :param approval_code: The approval_code of this OfflineProcessing.  # noqa: E501
        :type: str
        """

        self._approval_code = approval_code

