# coding: utf-8

from model.serializable import SwaggerSerializable


class OrderBreakdownUpdatableData(SwaggerSerializable):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tip': 'Tip'
    }

    attribute_map = {
        'tip': 'tip'
    }

    def __init__(self, tip=None):  # noqa: E501
        """OrderBreakdownUpdatableData - a model defined in Swagger"""  # noqa: E501
        self._tip = None
        self.discriminator = None
        if tip is not None:
            self.tip = tip

    @property
    def tip(self):
        """Gets the tip of this OrderBreakdownUpdatableData.  # noqa: E501


        :return: The tip of this OrderBreakdownUpdatableData.  # noqa: E501
        :rtype: Tip
        """
        return self._tip

    @tip.setter
    def tip(self, tip):
        """Sets the tip of this OrderBreakdownUpdatableData.


        :param tip: The tip of this OrderBreakdownUpdatableData.  # noqa: E501
        :type: Tip
        """

        self._tip = tip
