# coding: utf-8

import pprint

import six

from model.serializable import SwaggerSerializable


class Payload(SwaggerSerializable):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'payload_type': 'str',
        'account_type': 'str'
    }

    attribute_map = {
        'payload_type': 'payloadType',
        'account_type': 'accountType'
    }

    def __init__(self, payload_type=None, account_type='CHECKING'):  # noqa: E501
        """Payload - a model defined in Swagger"""  # noqa: E501
        self._payload_type = None
        self._account_type = None
        self.discriminator = None
        self.payload_type = payload_type
        if account_type is not None:
            self.account_type = account_type

    @property
    def payload_type(self):
        """Gets the payload_type of this Payload.  # noqa: E501


        :return: The payload_type of this Payload.  # noqa: E501
        :rtype: str
        """
        return self._payload_type

    @payload_type.setter
    def payload_type(self, payload_type):
        """Sets the payload_type of this Payload.


        :param payload_type: The payload_type of this Payload.  # noqa: E501
        :type: str
        """
        if payload_type is None:
            raise ValueError("Invalid value for `payload_type`, must not be `None`")  # noqa: E501

        self._payload_type = payload_type

    @property
    def account_type(self):
        """Gets the account_type of this Payload.  # noqa: E501


        :return: The account_type of this Payload.  # noqa: E501
        :rtype: str
        """
        return self._account_type

    @account_type.setter
    def account_type(self, account_type):
        """Sets the account_type of this Payload.


        :param account_type: The account_type of this Payload.  # noqa: E501
        :type: str
        """
        allowed_values = ["CHECKING", "SAVINGS"]  # noqa: E501
        if account_type not in allowed_values:
            raise ValueError(
                "Invalid value for `account_type` ({0}), must be one of {1}"  # noqa: E501
                .format(account_type, allowed_values)
            )

        self._account_type = account_type
