# coding: utf-8
from model.serializable import SwaggerSerializable


class UpdateCredentialsRequest(SwaggerSerializable):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'terminal': 'str',
        'operator': 'str',
        'customer': 'Customer',
        'customer_account': 'UpdatablePayload',
        'additional_data_fields': 'list[CustomField]'
    }

    attribute_map = {
        'terminal': 'terminal',
        'operator': 'operator',
        'customer': 'customer',
        'customer_account': 'customerAccount',
        'additional_data_fields': 'additionalDataFields'
    }

    def __init__(self, terminal=None, operator=None, customer=None, customer_account=None, additional_data_fields=None):  # noqa: E501
        """UpdateCredentialsRequest - a model defined in Swagger"""  # noqa: E501
        self._terminal = None
        self._operator = None
        self._customer = None
        self._customer_account = None
        self._additional_data_fields = None
        self.discriminator = None
        self.terminal = terminal
        if operator is not None:
            self.operator = operator
        if customer is not None:
            self.customer = customer
        if customer_account is not None:
            self.customer_account = customer_account
        if additional_data_fields is not None:
            self.additional_data_fields = additional_data_fields

    @property
    def terminal(self):
        """Gets the terminal of this UpdateCredentialsRequest.  # noqa: E501

        The number of the terminal which is the credentials' holder.  # noqa: E501

        :return: The terminal of this UpdateCredentialsRequest.  # noqa: E501
        :rtype: str
        """
        return self._terminal

    @terminal.setter
    def terminal(self, terminal):
        """Sets the terminal of this UpdateCredentialsRequest.

        The number of the terminal which is the credentials' holder.  # noqa: E501

        :param terminal: The terminal of this UpdateCredentialsRequest.  # noqa: E501
        :type: str
        """
        self._terminal = terminal

    @property
    def operator(self):
        """Gets the operator of this UpdateCredentialsRequest.  # noqa: E501

        The operator who initiated the transaction. If not sent in the request, this field will be automatically populated with the API Key alias.  # noqa: E501

        :return: The operator of this UpdateCredentialsRequest.  # noqa: E501
        :rtype: str
        """
        return self._operator

    @operator.setter
    def operator(self, operator):
        """Sets the operator of this UpdateCredentialsRequest.

        The operator who initiated the transaction. If not sent in the request, this field will be automatically populated with the API Key alias.  # noqa: E501

        :param operator: The operator of this UpdateCredentialsRequest.  # noqa: E501
        :type: str
        """

        self._operator = operator

    @property
    def customer(self):
        """Gets the customer of this UpdateCredentialsRequest.  # noqa: E501


        :return: The customer of this UpdateCredentialsRequest.  # noqa: E501
        :rtype: Customer
        """
        return self._customer

    @customer.setter
    def customer(self, customer):
        """Sets the customer of this UpdateCredentialsRequest.


        :param customer: The customer of this UpdateCredentialsRequest.  # noqa: E501
        :type: Customer
        """

        self._customer = customer

    @property
    def customer_account(self):
        """Gets the customer_account of this UpdateCredentialsRequest.  # noqa: E501


        :return: The customer_account of this UpdateCredentialsRequest.  # noqa: E501
        :rtype: UpdatablePayload
        """
        return self._customer_account

    @customer_account.setter
    def customer_account(self, customer_account):
        """Sets the customer_account of this UpdateCredentialsRequest.


        :param customer_account: The customer_account of this UpdateCredentialsRequest.  # noqa: E501
        :type: UpdatablePayload
        """

        self._customer_account = customer_account

    @property
    def additional_data_fields(self):
        """Gets the additional_data_fields of this UpdateCredentialsRequest.  # noqa: E501

        List of custom fields to add or update. An empty list will lead to the removal of any existing additional data associated with the credentials.  # noqa: E501

        :return: The additional_data_fields of this UpdateCredentialsRequest.  # noqa: E501
        :rtype: list[CustomField]
        """
        return self._additional_data_fields

    @additional_data_fields.setter
    def additional_data_fields(self, additional_data_fields):
        """Sets the additional_data_fields of this UpdateCredentialsRequest.

        List of custom fields to add or update. An empty list will lead to the removal of any existing additional data associated with the credentials.  # noqa: E501

        :param additional_data_fields: The additional_data_fields of this UpdateCredentialsRequest.  # noqa: E501
        :type: list[CustomField]
        """

        self._additional_data_fields = additional_data_fields
