# coding: utf-8
from model.serializable import SwaggerSerializable


class UpdatablePayload(SwaggerSerializable):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'source': 'str'
    }

    attribute_map = {
        'source': 'source'
    }

    discriminator_value_class_map = {
            'CARD'.lower(): '#/components/schemas/CardDetails',
    }

    def __init__(self, source='CARD'):  # noqa: E501
        """UpdatablePayload - a model defined in Swagger"""  # noqa: E501
        self._source = None
        self.discriminator = 'source'
        if source is not None:
            self.source = source

    @property
    def source(self):
        """Gets the source of this UpdatablePayload.  # noqa: E501


        :return: The source of this UpdatablePayload.  # noqa: E501
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this UpdatablePayload.


        :param source: The source of this UpdatablePayload.  # noqa: E501
        :type: str
        """

        self._source = source

    def get_real_child_model(self, data):
        """Returns the real base class specified by the discriminator"""
        discriminator_value = data[self.discriminator].lower()
        return self.discriminator_value_class_map.get(discriminator_value)
